name = "IGA"
uuid = "e7b8d123-e02a-40ba-ad18-d3943ed54f1c"
authors = ["Elias BÃ¶rjesson <elias.isak.borjesson@gmail.com>"]
version = "0.2.6"

[deps]
Ferrite = "c061ca5d-56c9-439f-9c0e-210fe06d3992"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Tensors = "48a634ad-e948-5137-8d70-aa71f2a747f4"
WriteVTK = "64499a7a-5c06-52f2-abe2-ccb03c286192"

[compat]
WriteVTK = "1.13"
