[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Ferrite = "c061ca5d-56c9-439f-9c0e-210fe06d3992"
IGA = "e7b8d123-e02a-40ba-ad18-d3943ed54f1c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
LiveServer = "16fef848-5104-11e9-1b77-fb7a48bbb589"
